coverage:
  ignore:
    - "frontend"
    - "backend/tests"
    - "backend/evaluation"
    - "**/container.py"
    - "**/router.py"
    - "**/api.py"
    - "**/cli.py"
    - "backend/repograph/utils/logging.py"
  status:
      project:
        default:
          target: auto
          threshold: 0%
          if_ci_failed: error
          informational: true
          only_pulls: false
      patch:
        default:
          target: auto
          threshold: 0%
          if_ci_failed: error
          informational: true
          only_pulls: false