coverage:
  ignore:
    - "frontend"
    - "backend/tests"
    - "backend/evaluation"
    - "**/container.py"
    - "**/router.py"
    - "**/api.py"
    - "**/cli.py"
    - "backend/utils/logging.py"
