repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: ^backend/repograph/tests/
        args:
          - "--max-line-length=100"
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: nosetests backend
        language: python
        "types": [python]
        pass_filenames: false
        additional_dependencies:
          [
            parameterized,
            py2neo,
            click,
            neo4j,
            pydantic,
            transformers,
            torch,
            nose,
            fastapi,
            dependency-injector,
          ]
        stages: [commit]
      - id: reindent
        name: reindent
        entry: reindent -r -n backend
        language: python
        "types": [python]
        additional_dependencies: [reindent]
        pass_filenames: false
        stages: [commit]
      - id: pdoc
        name: pdoc
        entry: pdoc backend/repograph --html -f -o backend/docs
        language: python
        "types": [python]
        pass_filenames: false
        stages: [commit]
        additional_dependencies:
          [
            pdoc3,
            pydantic,
            fastapi,
            py2neo,
            click,
            neo4j,
            transformers,
            sentence_transformers,
            torch,
            configargparse,
            dependency-injector,
            uvicorn,
          ]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
        exclude: ^backend
        args:
          - "frontend"
          - "--write"
        "types": [ javascript ]
        pass_filenames: false
        stages: [ commit ]
        additional_dependencies:
          - prettier@2.8.3
          - prettier-plugin-tailwindcss@0.2.1
