repos:
- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
- repo: local
  hooks:
  - id: unittest
    name: unittest
    entry: python3 -m unittest 
    language: python
    'types': [python]
    pass_filenames: false
    additional_dependencies: [parameterized, py2neo, click, neo4j, pydantic]
    stages: [commit]
  - id: reindent
    name: reindent
    entry: reindent -r -n repograph tests
    language: python
    'types': [python]
    additional_dependencies: [reindent]
    pass_filenames: false
    stages: [commit]