repos:
-   repo: https://github.com/PyCQA/flake8
    hooks:
    -   id: flake8

-   id: unittest
    name: unittest
    entry: python -m unittest 
    language: python
    'types': [python]
    pass_filenames: false
    stages: [commit]