services:
  neo4j:
    image: docker.io/library/neo4j
    container_name: neo4j
    environment:
      - VERSION=podman
      - NEO4J_AUTH=neo4j/s3cr3t
    restart: always
    ports: 
    - "7474:7474"
    - "7687:7687"