name: repograph
channels:
  - pytorch
  - huggingface
  - conda-forge
dependencies:
  - aom=3.5.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - colorama=0.4.6
  - cryptography=38.0.3
  - dataclasses=0.8
  - expat=2.5.0
  - ffmpeg=5.1.2
  - filelock=3.8.0
  - flake8=5.0.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - gettext=0.21.1
  - gmp=6.2.1
  - gnutls=3.7.8
  - huggingface_hub=0.11.0
  - icu=70.1
  - idna=3.4
  - importlib-metadata=5.0.0
  - importlib_metadata=5.0.0
  - joblib=1.2.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.14
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libdeflate=1.14
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.21.9
  - libsqlite=3.40.0
  - libtasn1=4.19.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libvpx=1.11.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=15.0.5
  - mccabe=0.7.0
  - ncurses=6.3
  - nettle=3.8.1
  - numpy=1.23.5
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.0.7
  - p11-kit=0.24.1
  - packaging=21.3
  - pillow=9.2.0
  - pip=22.3.1
  - protobuf=4.21.9
  - pthread-stubs=0.4
  - pycodestyle=2.9.1
  - pycparser=2.21
  - pyflakes=2.5.0
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.9.12
  - python_abi=3.9
  - pytorch=1.13.0
  - pyyaml=6.0
  - readline=8.1.2
  - regex=2022.10.31
  - requests=2.28.1
  - sacremoses=master
  - setuptools=65.5.1
  - six=1.16.0
  - sqlite=3.40.0
  - svt-av1=1.3.0
  - tk=8.6.12
  - tqdm=4.64.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022f
  - urllib3=1.26.11
  - wheel=0.38.4
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.10.0
  - zstd=1.5.2
  - pip:
    - cfgv==3.3.1
    - distlib==0.3.6
    - identify==2.5.9
    - interchange==2021.0.4
    - monotonic==1.6
    - neo4j==5.2.1
    - nodeenv==1.7.0
    - pansi==2020.7.3
    - parameterized==0.8.1
    - platformdirs==2.5.4
    - pre-commit==2.20.0
    - py2neo==2021.2.3
    - pydantic==1.10.2
    - pygments==2.13.0
    - pytz==2022.6
    - reindent==3.5.1
    - tokenizers==0.13.2
    - toml==0.10.2
    - transformers==4.24.0
    - virtualenv==20.16.7
