version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(levelname)s:%(name)s | %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout

loggers:
  uvicorn:
    error:
      propagate: true

root:
  level: ERROR
  handlers: [console]
  propagate: no