name: Code Coverage
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
